### ISSUE TITLE
Add ability to open application when interacting with a notification

### ISSUE THREAD

**Issue by ndizazzo** [ndizazzo/android-parse-titanium-module#18]
#### Current Behaviour
The application does not open when tapping a push notification. 

#### Desired Behaviour
The application should be opened, and an event should be triggered when a user interacts with a push notification.

**Comment by zabady** [comment]
Now the app opens when the notification get clicked, but is there a way to get the data of the push notifications, and what about the callback function?

Thanks in advance.

**Comment by ndizazzo** [comment]
Hey @zabady - This is something I want to address very soon. As of now, I don't think any callbacks or hooks exist for the Android parse module to provide for the application. 

I haven't gotten to that requirement in the application that drives development on this module, but it's coming up soon.

Issue #23 has been set up to track this feature.
